# Generated by Django 3.2 on 2021-05-25 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordereditem',
            old_name='quauntity',
            new_name='quantity',
        ),
    ]
