# Generated by Django 3.2 on 2021-05-25 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_item_category'),
        ('orders', '0002_rename_quauntity_ordereditem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.item'),
        ),
    ]
